// const images = [
//   require("./assets/gallery/image1.jpg").default,
//   require("./assets/gallery/image2.jpg").default,
//   require("./assets/gallery/image3.jpg").default,
//   require("./assets/gallery/image4.jpg").default,
//   require("./assets/gallery/image5.jpg").default,
//   require("./assets/gallery/image6.jpg").default,
//   require("./assets/gallery/image7.jpg").default,
//   require("./assets/gallery/image8.jpg").default,
//   require("./assets/gallery/image9.jpg").default,
//   require("./assets/gallery/image10.jpg").default,
//   require("./assets/gallery/image11.jpg").default,
//   require("./assets/gallery/image12.jpg").default,
//   require("./assets/gallery/image13.jpg").default,
//   require("./assets/gallery/image14.jpg").default,
//   require("./assets/gallery/image15.jpg").default,
//   require("./assets/gallery/image16.jpg").default,
//   require("./assets/gallery/image17.jpg").default,
//   require("./assets/gallery/image18.jpg").default,
//   require("./assets/gallery/image19.jpg").default,
//   require("./assets/gallery/image20.jpg").default,
//   require("./assets/gallery/image21.jpg").default,
//   require("./assets/gallery/image22.jpg").default,
//   require("./assets/gallery/image23.jpg").default,
//   require("./assets/gallery/image24.jpg").default,
//   require("./assets/gallery/image25.jpg").default,
//   require("./assets/gallery/image26.jpg").default,
//   require("./assets/gallery/image27.jpg").default,
//   require("./assets/gallery/image28.jpg").default,
//   require("./assets/gallery/image30.jpg").default,
// ];

// export default images;

const images = [
  "/assets/gallery/image1.jpg",
  "/assets/gallery/image2.jpg",
  "/assets/gallery/image3.jpg",
  "./assets/gallery/image4.jpg",
  "./assets/gallery/image5.jpg",
  "./assets/gallery/image6.jpg",
  "./assets/gallery/image7.jpg",
  "./assets/gallery/image8.jpg",
  "./assets/gallery/image9.jpg",
  "./assets/gallery/image10.jpg",
  "./assets/gallery/image11.jpg",
  "./assets/gallery/image12.jpg",
  "./assets/gallery/image13.jpg",
  "./assets/gallery/image14.jpg",
  "./assets/gallery/image15.jpg",
  "./assets/gallery/image16.jpg",
  "./assets/gallery/image17.jpg",
  "./assets/gallery/image18.jpg",
  "./assets/gallery/image19.jpg",
  "./assets/gallery/image20.jpg",
  "./assets/gallery/image21.jpg",
  "./assets/gallery/image22.jpg",
  "./assets/gallery/image23.jpg",
  "./assets/gallery/image24.jpg",
  "./assets/gallery/image25.jpg",
  "./assets/gallery/image26.jpg",
  "./assets/gallery/image27.jpg",
  "./assets/gallery/image28.jpg",
  "./assets/gallery/image30.jpg",
];

export default images;
